apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: apibook
  title: API Book
  description: API para gerenciamento de livros
  annotations:
    swagger.io/docs-url: http://localhost:5000/swagger
    github.com/project-slug: raftriani/ApiBook
spec:
  type: openapi
  lifecycle: experimental  
  owner: user:rafael.triani
  definition: |
    openapi: 3.0.1
    info:
      title: ApiBook
      version: 1.0.0
      description: API para gerenciamento de livros
    paths:
      /api/Book:
        get:
          summary: Lista livros
          responses:
            '200':
              description: OK
        post:
          summary: Cria livro
          responses:
            '200':
              description: OK
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: apibook-service
  title: ApiBook Service
  description: Serviço da API de livros
  annotations:
    github.com/project-slug: raftriani/ApiBook
spec:
  type: service
  lifecycle: experimental
  owner: user:rafael.triani
  providesApis:
    - apibook
