version: "3"

services: 

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: book-sql-server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "MeuDB@123"
      ACCEPT_EULA: "Y"

  api-book:
    image: "book-test:latest"
    container_name: "book"
    build:
      context: ""
      dockerfile: "./Dockerfile"
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:5000
      - ConnectionStrings__DefaultConnection=Server=sql-server;Database=Book;User Id=sa;Password=MeuDB@123;encrypt=false;
      - AWS_S3_KEY=QUtJQTNETU1FUkdLSlVCUkJUV1o6M3ZKbDFkSkhqUzNaZTNTKzRuRmpCeGZyMW10SEVkZCtPdE93WmUwdg==
    depends_on:
      - sql-server